version: '3'

services:

  nao-mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=login
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
#    ports:
#      - 3306:3306
    networks:
      - nao_network

  nao-main:
    build: .
    restart: on-failure
    depends_on:
      - nao-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=nao-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=login
      - DATABASE_PORT=3306
    networks:
      - nao_network

networks:
  nao_network:




